name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Decrypt input files
      env:
        DECRYPTION_KEY: ${{ secrets.INPUT_DECRYPTION_KEY }}
      run: |
        for file in $(find . -name "*.enc"); do
          # Decode from base64, extract IV and encrypted content
          decoded_content=$(base64 -d "$file")
          iv=$(echo "$decoded_content" | head -c 16 | xxd -p -c 32)
          encrypted_data=$(echo "$decoded_content" | tail -c +17)

          # Derive the key from the DECRYPTION_KEY and salt
          key=$(echo -n "$DECRYPTION_KEY" | xxd -p -c 256)

          # Use OpenSSL to decrypt
          echo "$encrypted_data" | openssl enc -aes-256-cbc -d -K "$key" -iv "$iv" -out "${file%.enc}"
        done

    - name: Run tests
      run: npm test
