name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Decrypt input files
      env:
        DECRYPTION_KEY: ${{ secrets.INPUT_DECRYPTION_KEY }}
      run: |
        for file in $(find . -name "*.enc"); do
          openssl enc -aes-256-cbc -d -in "$file" -out "${file%.enc}" -k "$DECRYPTION_KEY"
        done

    - name: Run tests
      run: npm test
